name: clean_architecture_tdd_course
description: A new Flutter project implementing Clean Architecture with TDD

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Service locator
  get_it: ^8.0.2

  # Bloc for state management
  flutter_bloc: ^8.1.6
  bloc: ^8.1.4

  # Value equality
  equatable: ^2.0.8

  # Functional programming thingies
  dartz: ^0.10.1

  # Remote API
  connectivity_plus: ^6.1.1  # connectivity is deprecated, use connectivity_plus
  http: ^1.2.2

  # Local cache
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  build_runner: ^2.4.13  # Required for mockito code generation
  flutter_lints: ^5.0.0  # Optional but recommended